version: '2.2'
services:

  akka-crud-service:
    image: cats_api:1.0.0-SNAPSHOT
    container_name: cats_api
    mem_limit: 2g
    environment:
      APP_CONFIG_PATH: /opt/conf/application.conf
    volumes:
      - ./config/application.conf:/opt/conf/application.conf
      - ./config/logback.xml:/opt/conf/logback.xml
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    restart: always
    image: library/postgres:13.1-alpine
    container_name: cats-api-service-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cats
      - POSTGRES_PASSWORD=cats
      - POSTGRES_DB=cats